### ISSUE TITLE
accessing services 

### ISSUE THREAD

**Issue by kadel** [procrypt/kompose-example#2]
You are using `$ curl <frontend-ip>:80` to test service. 
Problem with this is that it assumes that you run this command from machine inside the cluster. There should be note explaining this.
Or you can create route, that will expose that service. But this has to be done manually (`oc expose frontend`) because kompose doesn't support that yet (https://github.com/kubernetes-incubator/kompose/issues/140)

**Comment by procrypt** [comment]
@kadel Thanks i'll update the repo.

**Comment by procrypt** [comment]
@kadel PR updated.
